[tool.poetry]
name = "lenticular"
version = "0.1.0"
description = "ğŸ˜¶â€ğŸŒ«ï¸ A set of tools for fetching files from the cloud"
authors = ["apjanco <apjanco@upenn.edu>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
google-api-core = "^2.11.0"
tqdm = "^4.65.0"
mkdocs = "^1.4.2"
mkdocs-material = "^9.1.6"
google-api-python-client = "^2.85.0"
google-auth-oauthlib = "^1.0.0"
rich = "^13.3.4"
typer = "^0.7.0"
datasets = {extras = ["vision"], version = "^2.11.0"}
huggingface-hub = "^0.13.4"

[tool.poetry.scripts]
lenticular = "lenticular.cli:app"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
